### PR TITLE
St 162 cookies

### PR DESCRIPTION
**Pull request by alexdany657**

### CODE REVIEW

**Comment by cookiedoth** [comment]
я добавил "kek" в куку в произвольном месте, поймал 500

**Comment by cookiedoth** [comment]
[2019-05-04 13:11:00,734] ERROR in app: Exception on /home [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cookiedoth/prog/strategy-trial/app/routes/all.py", line 20, in home
    return render_template('home.html.j2', title = title, info = info())
  File "/Users/cookiedoth/prog/strategy-trial/app/forRoutes/info.py", line 19, in info
    a = decrypt(cookies).split()
  File "/Users/cookiedoth/prog/strategy-trial/app/forRoutes/hash.py", line 25, in decrypt
    message = str(rsa.decrypt(bytes.fromhex(hashed), key))[2:-1]
ValueError: non-hexadecimal number found in fromhex() arg at position 44
127.0.0.1 - - [04/May/2019 13:11:00] "GET /home HTTP/1.1" 500 -
[2019-05-04 13:11:00,751] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/usr/local/lib/python3.7/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/Users/cookiedoth/prog/strategy-trial/app/routes/all.py", line 151, in page_not_found
    return render_template('error404.html.j2', info = info()), 404
  File "/Users/cookiedoth/prog/strategy-trial/app/forRoutes/info.py", line 19, in info
    a = decrypt(cookies).split()
  File "/Users/cookiedoth/prog/strategy-trial/app/forRoutes/hash.py", line 25, in decrypt
    message = str(rsa.decrypt(bytes.fromhex(hashed), key))[2:-1]
ValueError: non-hexadecimal number found in fromhex() arg at position 44
127.0.0.1 - - [04/May/2019 13:11:00] "GET /favicon.ico HTTP/1.1" 500 -

**Comment by cookiedoth** [comment]
Screenshot 2019-05-04 at 13 14 34

BAN

**Comment by cookiedoth** [comment]
Короче надо исправить RE при не hex куке.

Остальное работает.

**Comment by alexdany657** [comment]
Ок, ща исправлю

**Comment by alexdany657** [comment]
Исправил

**Comment by cookiedoth** [comment]
Работает

**Pull request merged**
